.slather.yml, .travis.yml, scripts/push-documentation.sh
Adding automated code coverage report using Slather.org.
Relates to: #MOBILE-625
=> Add automated code coverage report

README.md
Adds a quick note on how to use the Gini SDK with Xcode 8 and iOS 10 to the docs.
See the readme for changes.
Nothing to be considered.
MOBILE-589, MOBILE-660
=> Add some notes about iOS10

Documentation/Makefile, Documentation/requirements.txt, Documentation/source/guide-for-open-with.rst, Documentation/source/index.rst
A guide for adding "Open with..." for PDFs and images to an iOS app.
=> Guide for open with

Example/GiniVision/AppDelegate.swift, Example/GiniVision/Base.lproj/Main.storyboard, Example/GiniVision/ComponentAPICameraViewController.swift, Example/GiniVision/ComponentAPIReviewViewController.swift, Example/GiniVision/Info.plist, Example/GiniVision/ScreenAPIViewController.swift, GiniVision/Assets/Localizable.strings, GiniVision/Classes/FilePickerManager.swift, GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/GiniVision.swift, GiniVision/Classes/GiniVisionDocument.swift, GiniVision/Classes/ReviewContainerViewController.swift, GiniVision/Classes/ReviewViewController.swift
From external apps there is always an option to export a resource to another different app, so this feature enables the Example app to be discoverable by other apps and adds ways to handle incoming files by GVL. 
For the Example app is only possible to handle files from ScreenAPIViewController, since it is a GiniVisionDelegate.
Try export an image or pdf from other app to Example app.
Automatic.
Issue #51
=> File import with "Open with..."

Example/GiniVision/AppDelegate.swift, Example/GiniVision/ScreenAPIViewController.swift, Example/Tests/GINIMetaInformationManagerTests.swift, Example/Tests/GiniVisionDocumentTests.swift, GiniVision/Classes/AnalysisViewController.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/FilePickerManager.swift, GiniVision/Classes/GiniImageDocument.swift, GiniVision/Classes/GiniPDFDocument.swift, GiniVision/Classes/GiniVision.swift, GiniVision/Classes/GiniVisionDocument.swift, GiniVision/Classes/ImageMetaInformationManager.swift, GiniVision/Classes/ReviewViewController.swift
To be able to determine where the image comes, `Source` and `ImportMethod` keys have been added to the user comment.
Take a picture or import an image an see that this new keys have been added correctly to the metaInformation.
Automatic.
Issue #58
=> New fields on MetaInformation EXIF

Example/GiniVision/ScreenAPIViewController.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/GiniConfiguration.swift
File import feature should be enabled through `GiniConfiguration`, being disabled by default.
Set `enabledFileImport` to `true` and see that file import feature is enabled. Then set it to `false` and see that it is disabled.
Automatic.
Issue #59
=> File import toggle

GiniVision/Classes/AnalysisContainerViewController.swift, GiniVision/Classes/AnalysisViewController.swift, GiniVision/Classes/Camera.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/CaptureSuggestionsView.swift, GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/PDFInformationView.swift, GiniVision/Classes/ToolTipView.swift
Analysis screen UI has been improved, showing the PDF information above image instead of over, and the capture suggestions appearance animation has been modified.
Fixed also some issues.
Import a PDF and see that the title and page count is shown above the image and an indicator with a white background is shown in the middle of the image. Also import or take a picture and see after 4 seconds that some tips appear on the bottom.
Automatic.
Issues #65, #66
=> Finalize UI

Documentation/source/Open with guide.md, Example/GiniVision.xcodeproj/project.pbxproj, Example/GiniVision/SelectAPIViewController.swift, Example/Tests/Extensions.swift, Example/Tests/GINIHelpMenuViewControllerTests.swift, Example/Tests/GINIPDFDocumentTests.swift, Example/Tests/GiniVisionDocumentTests.swift, GiniVision/Assets/Localizable.strings, GiniVision/Classes/CameraContainerViewController.swift, GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/GiniVision.swift, GiniVision/Classes/HelpMenuViewController.swift
Added new no help menu screen on Camera Screen.
Go to Camera screen and press Hilfe button.
Automatic.
Issue #88.
=> Help menu screen

.jazzy.json, Documentation/Sections/Documentation.md, Documentation/source/Open with guide.md, Documentation/source/Updating to 3.2.0.md
Added new migration guide for 3.2.0 version.
Build the documentation (scripts/build-documentation-api.sh) and load the index.html inside Api folder.
Automatic.
Issue #99 .
=> Migration guide

.jazzy.json, Documentation/source/Updating to 3.2.0.md, GiniVision/Classes/AnalysisViewController.swift, GiniVision/Classes/CameraNotAuthorizedView.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/CaptureSuggestionsCollectionCell.swift, GiniVision/Classes/CaptureSuggestionsCollectionHeader.swift, GiniVision/Classes/GiniBarButtonItem.swift, GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/GiniNavigationViewController.swift, GiniVision/Classes/GiniVisionFont.swift, GiniVision/Classes/ImageAnalysisNoResultsViewController.swift, GiniVision/Classes/NoticeView.swift, GiniVision/Classes/OnboardingPage.swift, GiniVision/Classes/ReviewViewController.swift
Added a custom font that simplifies the way to use your own typography for your app.
Automatic.
Issue #95 .
=> Generic custom font

GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/GiniVisionUtils.swift
Sorted all properties in GiniConfiguration so in the documentation it will be more clear. Also moved Colors class to GiniVisionUtils.
Issue #107
=> Sort properties inside GiniConfiguration

Documentation/Sections/Documentation.md, Documentation/source/Updating to 3.2.0.md, README.md
Added link to assets repository in the documentation.
Automatic.
=> Add link to ui assets repository in the documentation

GiniVision/Classes/ReviewViewController.swift
Fix issue with double tapping on Review screen.
Run the app, take a picture and double tap it on the review screen
Automatic.
#115
=> Fixed issue with double tap.

Example/GiniVision/Base.lproj/Main.storyboard, GiniVision/Classes/AnalysisViewController.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/CaptureSuggestionsView.swift, GiniVision/Classes/ImageAnalysisNoResultsViewController.swift, GiniVision/Classes/ReviewViewController.swift
Fix issue with view controllers bottom layout, that affected directly to the iPhone X.
Run the app with an iPhone X and there should be a proper margin in the bottom.
Automatic.
#117
=> Fix iPhone X layout

GiniVision/Classes/AnalysisContainerViewController.swift, GiniVision/Classes/AnalysisViewController.swift, GiniVision/Classes/CameraContainerViewController.swift, GiniVision/Classes/CameraNotAuthorizedView.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/CaptureSuggestionsCollectionCell.swift, GiniVision/Classes/CaptureSuggestionsCollectionHeader.swift, GiniVision/Classes/CaptureSuggestionsView.swift, GiniVision/Classes/GiniVisionUtils.swift, GiniVision/Classes/ImageAnalysisNoResultsContainerViewController.swift, GiniVision/Classes/ImageAnalysisNoResultsViewController.swift, GiniVision/Classes/NoticeView.swift, GiniVision/Classes/OnboardingContainerViewController.swift, GiniVision/Classes/OnboardingPage.swift, GiniVision/Classes/OnboardingViewController.swift, GiniVision/Classes/OpenWithTutorialCollectionCell.swift, GiniVision/Classes/OpenWithTutorialCollectionHeader.swift, GiniVision/Classes/PDFInformationView.swift, GiniVision/Classes/ReviewContainerViewController.swift, GiniVision/Classes/ReviewViewController.swift, GiniVision/Classes/SupportedFormatsTableViewCell.swift, GiniVision/Classes/ToolTipView.swift
In order to make the code more readable, constraints utils class has been refactored so now it has shorter methods.
Automatic.
=> Rename constraint utils class.

Example/Tests/GINICameraViewControllerTests.swift, GiniVision/Classes/Camera.swift, GiniVision/Classes/CameraViewController.swift
Added QR scanning in Camera class.
Scan a QR code and see that is returned in the captureOutput delegate.
Automatic.
#122
=> Add QR Scanning in Camera

Example/GiniVision.xcodeproj/project.pbxproj, Example/GiniVision/AppCoordinator.swift, Example/GiniVision/Base.lproj/Main.storyboard, Example/GiniVision/ScreenAPICoordinator.swift, Example/GiniVision/SettingsViewController.swift, Example/Tests/GINIQRCodeDocumentTests.swift, Example/Tests/GINISettingsViewControllerTests.swift, Example/Tests/GINIVisionDocumentTests.swift, GiniVision/Assets/Localizable.strings, GiniVision/Classes/Camera.swift, GiniVision/Classes/CameraContainerViewController.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/Extensions/String.swift, GiniVision/Classes/Extensions/UIImage.swift, GiniVision/Classes/Extensions/URL.swift, GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/GiniError.swift, GiniVision/Classes/GiniQRCodeDocument.swift, GiniVision/Classes/GiniVision.swift, GiniVision/Classes/GiniVisionDocument.swift, GiniVision/Classes/GiniVisionUtils.swift, GiniVision/Classes/IBANValidator.swift, GiniVision/Classes/QRCodeDetectedPopupView.swift, GiniVision/Classes/QRCodesExtractor.swift
Added QR processing, with a custom view por the popup in the camera screen.
Scan a valid QR code and see that a popup appears, being able to proceed to results.
Automatic.
#121
=> QR Processing

GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/QRCodeDetectedPopupView.swift
Added QR code background color and text color properties to `GiniConfiguration`.
Changed gini configuration properties and run the app to see the changes when detecting a QR code.
Automatic.
=> Finalize QR code UI

.jazzy.json, Documentation/Sections/Documentation.md, Documentation/source/Updating to 3.2.md, Example/GiniVision/AppCoordinator.swift, Example/GiniVision/ComponentAPIAnalysisViewController.swift, Example/Podfile.lock, ExampleObjC/GiniVisionExampleObjC.xcodeproj/project.pbxproj, ExampleObjC/GiniVisionExampleObjC/ScreenAPIViewController.m, ExampleObjC/Podfile.lock, GiniVision/Classes/AnalysisContainerViewController.swift, GiniVision/Classes/AnalysisViewController.swift, GiniVision/Classes/CameraNotAuthorizedView.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/CaptureSuggestionsCollectionCell.swift, GiniVision/Classes/GiniBarButtonItem.swift, GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/GiniError.swift, GiniVision/Classes/GiniNavigationViewController.swift, GiniVision/Classes/GiniVisionDocument.swift, GiniVision/Classes/GiniVisionFont.swift, GiniVision/Classes/ImageMetaInformationManager.swift, GiniVision/Classes/NoticeView.swift, GiniVision/Classes/OnboardingPage.swift, GiniVision/Classes/ReviewViewController.swift, Jenkinsfile
There were some issues with the visibility of some enums and classes in Objective C projects.
Open the ObjC example app and try to use these enums and classes.
Automatic.
#133
=> Hotfix enum visibility

Documentation/source/License.md, GiniVision/Classes/QRCodeDetectedPopupView.swift, Jenkinsfile, LICENSE
Updated license, fixed issue in Jenkinsfile.
Automatic.
Issue #137
=> Update license, fixed jenkinsfile and small ui issue.

Example/GiniVision/Base.lproj/Main.storyboard, Example/GiniVision/ComponentAPIAnalysisViewController.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/GiniQRCodeDocument.swift, GiniVision/Classes/QRCodeDetectedPopupView.swift
Changed behavior of the QR code scanning (now a QR code can be scanned again after the first 10 seconds), fixed issue with Component API and added mandatory iban for QR code validation.
Run the example app, scan a QR code and wait 10 seconds until it disappears. 
Automatic.
Issue #139
=> Final UI fixes with QR codes.

Example/GiniVision/AppCoordinator.swift, Example/GiniVision/Base.lproj/LaunchScreen.xib, Example/GiniVision/Base.lproj/Main.storyboard, Example/GiniVision/SettingsViewController.swift, Example/Tests/GINISettingsViewControllerTests.swift, Example/Tests/GalleryCoordinatorTests.swift, Example/Tests/GiniScreenAPICoordinatorTests.swift, GiniVision/Classes/Core/CameraViewController+Constraints.swift, GiniVision/Classes/Core/CameraViewController.swift, GiniVision/Classes/Core/FilePickerManager.swift, GiniVision/Classes/Core/Gallery/GalleryCoordinator.swift, GiniVision/Classes/Core/Gallery/ImagePickerCollectionViewCell.swift, GiniVision/Classes/Core/Gallery/ImagePickerViewController.swift, GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator.swift
Since the multipage feature will be optional, it has been added a toggle to enable/disable it along with different check in all multipage related screens.
Run the app and try to use the multipage feature. Go to Setting from the API selection screen and disable the multipage feature. After that try to use the multipage and see that it is not possible.
Automatic
Issue #172
=> Multipage feature toggle

Example/GiniVision/DocumentService.swift, Example/Podfile, Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/Networking/APIService.swift, GiniVision/Classes/Networking/Extensions/GiniScreenAPICoordinator+Networking.swift
The API SDK was updated with several changes (Bolts and Cancellation token) that has to be reflected in the GVL.
Run the app and try to analyze a document.
Automatic
Issue #178
=> Adapt API SDK changes

Example/GiniVision.xcodeproj/project.pbxproj, Example/GiniVision/DocumentService.swift, Example/Tests/ReviewViewControllerDelegateMock.swift, Example/Tests/ReviewViewControllerTests.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator+Review.swift, GiniVision/Classes/Core/ReviewViewController.swift, Jenkinsfile
In order to be consistent with the rest of screens, it has been added a delegate for the `ReviewViewController`.
Automatic
=> Add review controller delegate

Example/GiniVision.xcodeproj/project.pbxproj, Example/Podfile.lock, GiniVision/Classes/OnboardingContainerViewController.swift, GiniVision/Classes/OnboardingViewController.swift
When VoiceOver is enabled, there was an issue when trying to go to the next Onboarding tip after moving to a different accesibility element.
Install the Example app (fresh install), enable VoiceOver in iOS settings, open the app and try to use the Next button after moving from a label to another.
Automatic
=> Fix issue with Next button when VoiceOver is enabled

Documentation/source/Changelog.md, Example/GiniVision.xcodeproj/project.pbxproj, Example/GiniVision/Info.plist, Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/GiniVisionVersion.swift, GiniVision/Classes/OnboardingContainerViewController.swift, GiniVision/Classes/OnboardingViewController.swift
Added last changes from `develop` and updated .podspec file and `GiniVisionVersion`
Automatic
=> Release 3.3.3

Documentation/source/Changelog.md, Example/GiniVision/Info.plist, GiniVision.podspec, GiniVision/Classes/GiniVisionVersion.swift
Updated library to `3.3.3` (podspec, changelog...)
Automatic
=> Updated library to 3.3.3

Example/GiniVision.xcodeproj/project.pbxproj, Example/Tests/CapturedImagesStackViewTests.swift, Example/Tests/GINIMultipageReviewControllerTests.swift, Example/Tests/ImagePickerCollectionViewCellTests.swift, Example/Tests/MultipageReviewPagesCollectionCellTests.swift, GiniVision/Classes/Core/AnalysisViewController.swift, GiniVision/Classes/Core/CameraViewController.swift, GiniVision/Classes/Core/CapturedImagesStackView.swift, GiniVision/Classes/Core/Gallery/ImagePickerCollectionViewCell.swift, GiniVision/Classes/Core/GiniBarButtonItem.swift, GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/GiniNavigationViewController.swift, GiniVision/Classes/Core/Multipage Review/MultipageReviewPagesCollectionCell.swift, GiniVision/Classes/Core/Multipage Review/MultipageReviewViewController.swift, GiniVision/Classes/Core/ReviewViewController.swift
Some customizations have been added to new screens like Multipage review screen. Also has been fixed the value of the view controllers background.
Change the value of these custom properties in the `GiniConfiguration` and check that they change in the view.
Automatic
=> Add missing customizations

Example/Example ObjC/ScreenAPIViewController.m, Example/Example Swift/ComponentAPICoordinator.swift, Example/Example Swift/ScreenAPICoordinator.swift, GiniVision/Assets/Localizable.strings, GiniVision/Classes/Core/CameraViewController.swift, GiniVision/Classes/Core/CaptureSuggestionsCollectionView.swift, GiniVision/Classes/Core/CaptureSuggestionsView.swift, GiniVision/Classes/Core/ContainerNavigationController.swift, GiniVision/Classes/Core/DocumentPickerCoordinator.swift, GiniVision/Classes/Core/DocumentRequest.swift, GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/GiniError.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator+Camera.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator+Review.swift, GiniVision/Classes/Core/GiniVision.swift, GiniVision/Classes/Core/GiniVisionDocument.swift, GiniVision/Classes/Core/Multipage Review/MultipageReviewViewController.swift, GiniVision/Classes/Core/NoticeView.swift, GiniVision/Classes/Core/ReviewViewController.swift, GiniVision/Classes/Networking/Extensions/GiniScreenAPICoordinator+Networking.swift, GiniVision/Classes/Networking/Extensions/GiniVision+GiniVisionDelegate.swift, GiniVision/Classes/Networking/GiniClient.swift, GiniVision/Classes/Networking/PartialDocumentInfo.swift, GiniVision/Classes/Networking/Pinning/GiniVision+Pinning.swift
Added missing comments in some classes of the Gini Vision Library. Additionally renamed some methods and properties to make them more clear and consistent.
Run `pod install` and see that everything is created successfully and the projects builds.
Automatic
=> Added missing comments and renamed methods and properties

.github/pull_request_template.md
Added template for pull requests description
Automatic
=> Added template for pull request description

Documentation/deploy-documentation.sh, Documentation/source/Changelog.md, Example/GiniVision/Info.plist, GiniVision.podspec, GiniVision/Classes/GiniVisionVersion.swift
Library version updated to 3.3.4 (podspec and changelog)
Automatic
#248
=> Update GVL version to 3.3.4 (after #248)

Documentation/source/Changelog.md, Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Core/Multipage Review/MultipageReviewViewController.swift
Bumped library version to `4.0.0-beta.2`
Automatic
=> Release beta 2

Documentation/source/Import PDFs and images guide.md, Documentation/source/Updating to 4.0.md
In order to help users to update to the new version, a migration guide has been added. Both new features and breaking changes has been described in it.
Run "jazzy --config .jazzy.json" in the project root directory.
Automatic
=> Update to 4.0 guide

Jenkinsfile
When running 'pod repo update' in different builds at the same time, one of the build failed since they were trying to access the same resource.
Run two branches in parallel.
Automatic
=> Fix concurrent builds issue

Documentation/source/Changelog.md, GiniVision.podspec, GiniVision/Classes/GiniVisionVersion.swift
Bumped GVL version to 3.3.5
Automatic
=> Bumped version to 3.3.5

scripts/build-number-bump.sh
Changed info plist location to fix issue with Hockey upload for develop branch.
Run the _build-number-bump.sh_ script.
Automatic
=> Fix issue with Hockey upload for develop branch

Documentation/source/Changelog.md, Example/Example ObjC/Info.plist, Example/Example Swift/Info.plist, Example/GiniVision.xcodeproj/project.pbxproj, Example/Podfile, Example/Podfile.lock, Example/Tests/DocumentServiceMock.swift, GiniVision.podspec, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Core/Screens/Document picker/Gallery/GalleryCoordinator.swift, Jenkinsfile
Release 4.0.2 update which includes:
-  Fixed issue with _Open_ button text color in `ImagePickerViewController`
-  Fixed issue with the _Podfile_ in the Example app
-  Fixed IPA file name for Example app in the Jenkins file (Hockey)
Automatic
=> Release 4.0.2

Documentation/source/Changelog.md, Example/Example Swift/Info.plist, Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Core/Screens/Document picker/DocumentPickerCoordinator.swift
Added customizable tint color for navigation bar in Document explorer
Automatic
=> Release 4.3.1

Documentation/source/Changelog.md, Example/Example Swift/Info.plist, GiniVision.podspec, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Core/Screens/Analysis/AnalysisViewController.swift, GiniVision/Classes/Core/Screens/Camera/CameraViewController.swift, GiniVision/Classes/Core/Screens/Onboarding/OnboardingPage.swift, GiniVision/Classes/Core/Screens/Onboarding/OnboardingViewController.swift, GiniVision/Classes/Core/Screens/Review/ReviewViewController.swift
-   Fixed issue with non exposed ObjC members.
Automatic
=> Release 4.3.2

Example/Example Swift/ComponentAPIDocumentServiceProtocol.swift, Example/Example Swift/ComponentAPIDocumentsService.swift, Example/Tests/DocumentServiceMock.swift, GiniVision.podspec, GiniVision/Classes/Networking/AccountingDocumentService.swift, GiniVision/Classes/Networking/DocumentService.swift, GiniVision/Classes/Networking/DocumentServiceProtocol.swift
Add missing dependency Bolts Framework
Automatic
=> Add Bolts Framework as Dependency

GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/Screens/Help/HelpMenuViewController.swift, GiniVision/Classes/Core/Screens/Help/No results /ImageAnalysisNoResultsViewController.swift, GiniVision/Classes/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift, GiniVision/Tests/HelpMenuViewControllerTests.swift
Added flag in the `GiniConfiguration` to disable the Supported formats screen.
Set the `shouldShowSupportedFormatsScreen` to false and check that the screen is not shown.
Automatic
=> Make the supported formats screen optional

Documentation/source/Changelog.md, Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift
Which includes the following changes:
- Fixed issue with Onboarding modal transition style.
Automatic
=> Release 4.4.1

GiniVision/Classes/Core/Screens/Camera/CameraButtonsViewController.swift, GiniVision/Classes/Core/Screens/Camera/CapturedImagesStackView.swift, GiniVision/Classes/Core/Screens/Multipage Review/MultipageReviewPagesCollectionFooter.swift
Both in the camera and multipage review screen, there were some breaking constraints. 
Run the app and check that the log output does not show any constraint issue.
Automatic
=> Fix breaking constraints

GiniVision/Classes/Core/Screens/Camera/CameraViewController.swift
Added haptic feedback when an image is captured.
Take a picture of an image (with an iPhone 7 or newer), and check the haptic feedback.
Automatic
=> Added haptic feedback when an image is captured

Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/Core/Helpers/GiniVisionDocumentValidator.swift, GiniVision/Classes/Core/Helpers/QRCodesExtractor.swift, GiniVision/Classes/Core/Models/GiniQRCodeDocument.swift, GiniVision/Classes/Networking/AnalysisResult.swift, GiniVision/Classes/Networking/Extensions/GiniScreenAPICoordinator+Networking.swift, GiniVision/Classes/Networking/Extensions/GiniVision+GiniVisionDelegate.swift
Add EPS QR code support (https://members.stuzza.at/eservice/shops/eps4mobile/demo/index.php)
Generate a QR code in the website linked above, and scan it.
Merge after #327
=> Add EPS QR code support

GiniVision.podspec, GiniVision/Classes/Networking/Extensions/GiniVision+GiniVisionDelegate.swift
Add credentials removal method to `GiniVision` class.
Call the recently created method and check that the stored credentials are removed
Automatic
=> Add credentials removal method to GiniVision class.

Documentation/source/Changelog.md, Example/Example Swift/Info.plist, Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Core/Helpers/GiniVisionDocumentValidator.swift, GiniVision/Classes/Core/Helpers/QRCodesExtractor.swift, GiniVision/Classes/Core/Models/GiniQRCodeDocument.swift, GiniVision/Classes/Networking/AnalysisResult.swift, GiniVision/Classes/Networking/Extensions/GiniScreenAPICoordinator+Networking.swift, GiniVision/Classes/Networking/Extensions/GiniVision+GiniVisionDelegate.swift
This update has the following changes:
-   Added EPS QR code detection support.
-   Added client credential deletion possibility in the Networking plugin.
Nothing to test here.
Automatic
=> Release 4.7.0

Documentation/source/Changelog.md, Example/Example Swift/AppCoordinator.swift, Example/Example Swift/Info.plist, Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Core/Screens/Document picker/DocumentPickerCoordinator.swift
This release introduces the following changes:
- Fixed navigation bar appearance issue after opening a document from the file browser.
Automatic
=> Release 4.7.1

GiniVision/Classes/Core/Helpers/QRCodesExtractor.swift, GiniVision/Classes/Core/Models/GiniQRCodeDocument.swift, GiniVision/Classes/Networking/AnalysisResult.swift
Fixes the EPS QR code url and adds documentation for the `GiniQRCodeDocument`
Automatic
=> Fix QR code url key name

Documentation/source/Changelog.md, Example/Example Swift/Info.plist, GiniVision.podspec, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Core/Helpers/QRCodesExtractor.swift, GiniVision/Classes/Core/Models/GiniQRCodeDocument.swift, GiniVision/Classes/Networking/AnalysisResult.swift
This release includes the following changes:
- Renamed EPS QR Code url extraction name to `epsPaymentQRCodeUrl'
Automatic
=> Release 4.7.2

GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/Screens/Camera/Camera.swift, GiniVision/Classes/Core/Screens/Camera/CameraButtonsViewController.swift, GiniVision/Tests/CameraButtonsViewControllerDelegateMock.swift, GiniVision/Tests/CameraButtonsViewControllerTests.swift
Add the flash ON by default flag in the `GiniConfiguration`.
Disable the flash on by default in the `AppCoordinator` and check the flash is disabled on start.
Automatic
=> Add flash ON by default flag

GiniVision/Classes/Core/Custom views/NoticeView.swift, GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/Models/GiniError.swift, GiniVision/Classes/Core/Models/GiniVisionDocument.swift, GiniVision/Classes/Core/Screens/Analysis/AnalysisViewController.swift, GiniVision/Classes/Core/Screens/Camera/CameraButtonsViewController.swift, GiniVision/Classes/Core/Screens/Camera/CameraNotAuthorizedView.swift, GiniVision/Classes/Core/Screens/Camera/CameraViewController.swift, GiniVision/Classes/Core/Screens/Help/HelpMenuViewController.swift, GiniVision/Classes/Core/Screens/Onboarding/OnboardingContainerViewController.swift, GiniVision/Classes/Core/Screens/Onboarding/OnboardingPage.swift, GiniVision/Classes/Core/Screens/Review/ReviewViewController.swift, GiniVision/Classes/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift, GiniVision/Classes/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Review.swift, GiniVision/Tests/HelpMenuViewControllerTests.swift, GiniVision/Tests/ReviewViewControllerTests.swift
Old deprecated code has been removed, adapting the tests when needed.
Check that all the fonts and texts are ok.
Automatic
=> Remove old deprecated code

.jazzy.json, Documentation/Sections/Documentation.md, Documentation/Sections/Migration guides.md, Documentation/source/Updating to 5.0.md
The migration guide for the newest version of the GVL.
Automatic
=> Migration guide 5.0.0

Documentation/source/Integration.md, GiniVision/Classes/Core/GiniVisionVersion.swift
Fix version number and repo url in integration guide
Automatic
=> Fix version number and repo url

Documentation/source/Changelog.md, Example/GiniVision.xcodeproj/xcshareddata/xcschemes/Example ObjC.xcscheme, Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Core/Models/GiniQRCodeDocument.swift, Jenkinsfile, scripts/pod-lint.sh
=> Release 5.0.0

GiniVision/Classes/Core/Screens/Camera/Camera.swift
Apple doesn't guarantee that the completion closure from `captureStillImageAsynchronously` returns on the main thread, but the code goes onto doing UI from it directly.
It turns out for some iOS and hardware combinations the closure isn't on the main thread.
=> PIA-404: App crashes when taking a picture

Example/Example Swift/ComponentAPICoordinator.swift, GiniVision/Classes/Core/Screens/Camera/CameraViewController.swift, GiniVision/Classes/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift
This went bad when moving the camera access question to after the onboarding.
=> Fix Component API

GiniVision/Assets/de.lproj/Localizable.strings, GiniVision/Assets/de.lproj/Localizable.stringsdict, GiniVision/Assets/en.lproj/Localizable.strings, GiniVision/Assets/en.lproj/Localizable.stringsdict, GiniVision/Classes/Core/Screens/Digital Invoice/CheckboxButton.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DeselectLineItemActionSheet.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoice.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceFooterCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceHeaderCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceItemsCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceTotalPriceCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceViewController.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalLineItemTableViewCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalLineItemTableViewCell.xib, GiniVision/Classes/Core/Screens/Digital Invoice/LineItemDetailsViewController.swift
English copy can be reviewed here. The German strings are in English atm pending translation.
=> PIA-438: Prepared return assistant for localization.

GiniVision.podspec, GiniVision/Tests/HelpMenuViewControllerTests.swift
Explanation in ticket https://ginis.atlassian.net/browse/PIA-469
=> PIA-469: Fix pod lint for GVL 5

Jenkinsfile
A few updates including one semi-experimental trying to avoid `repo update` every time which lasts forever. It will run periodically anyway and in case of a problem it will run `repo update` and the build will have to be rerun manually. Overall seems like a good tradeoff atm. I'd like to try living with it for a bit.
=> Updates to the Jenkinsfile

.jazzy.json, Documentation/Sections/Documentation.md, Documentation/Sections/Guides.md, Documentation/source/Event tracking guide.md, Example/.swiftlint.yml, Example/Example Swift/ComponentAPICoordinator.swift, Example/Example Swift/ScreenAPICoordinator.swift, GiniVision/Classes/Core/Screens/Analysis/AnalysisViewController.swift, GiniVision/Classes/Core/Screens/Analysis/CaptureSuggestionsView.swift, GiniVision/Classes/Core/Screens/Camera/Camera.swift, GiniVision/Classes/Core/Screens/Camera/CameraButtonsViewController.swift, GiniVision/Classes/Core/Screens/Camera/CameraPreviewViewController.swift, GiniVision/Classes/Core/Screens/Camera/CameraViewController.swift, GiniVision/Classes/Core/Screens/Camera/QRCodeDetectedPopupView.swift, GiniVision/Classes/Core/Screens/Document picker/Gallery/AlbumsPickerTableViewCell.swift, GiniVision/Classes/Core/Screens/Document picker/Gallery/GalleryCoordinator.swift, GiniVision/Classes/Core/Screens/Onboarding/OnboardingContainerViewController.swift, GiniVision/Classes/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Analysis.swift, GiniVision/Classes/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift, GiniVision/Classes/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Review.swift, GiniVision/Classes/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift, GiniVision/Classes/Core/Tracking/Event.swift, GiniVision/Classes/Core/Tracking/GiniVisionTrackingDelegate.swift, GiniVision/Classes/Networking/Extensions/GiniVision+GiniVisionDelegate.swift, GiniVision/Classes/Networking/GiniNetworkingScreenAPICoordinator.swift
Updated all of the `guard let `self` = self` in a separate commit.
=>  PIA-486: As a loyalty partner, I would like to track events on iOS.

GiniVision/Classes/Networking/DocumentService.swift
Feedback sending was broken since version 5.0.0. Fix was fortunately simple as the bug has been introduced via a simple oversight.
[PIA-749](https://ginis.atlassian.net/browse/PIA-759)
=> Fixes feedback sending

Example/Example Swift/ComponentAPICoordinator.swift, Example/Example Swift/ComponentAPIDocumentServiceProtocol.swift, Example/Example Swift/ComponentAPIDocumentsService.swift, Example/Podfile.lock, GiniVision/Classes/Networking/AccountingDocumentService.swift, GiniVision/Classes/Networking/DocumentService.swift, GiniVision/Classes/Networking/DocumentServiceProtocol.swift, GiniVision/Classes/Networking/GiniNetworkingScreenAPICoordinator.swift
Allows sending feedback for compound extractions like line items.
[PIA-505](https://ginis.atlassian.net/browse/PIA-505)
=> Feedback for line items

GiniVision/Assets/de.lproj/Localizable.strings, GiniVision/Assets/de.lproj/Localizable.stringsdict, GiniVision/Assets/en.lproj/Localizable.strings, GiniVision/Assets/en.lproj/Localizable.stringsdict, GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/Helpers/Localization/String Resources/DigitalInvoiceStrings.swift, GiniVision/Classes/Core/Screens/Digital Invoice/CheckboxButton.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoice.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceAddon.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceAddonCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceFooterCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceHeaderCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceItemsCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceTotalPriceCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceViewController.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalLineItemTableViewCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/LineItemDetailsViewController.swift, GiniVision/Classes/Core/Screens/Digital Invoice/Price.swift
Shows addon extractions and adds their amounts to the final price.
[PIA-739](https://ginis.atlassian.net/browse/PIA-739)
=> Pia 739 addon extractions

Example/Podfile.lock, GiniVision.podspec, GiniVision/Assets/de.lproj/Localizable.strings, GiniVision/Assets/en.lproj/Localizable.strings, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Core/Screens/Camera/Camera.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DeselectLineItemActionSheet.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoice.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceViewController.swift, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalLineItemTableViewCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/LineItem.swift, GiniVision/Classes/Core/Screens/Digital Invoice/LineItemDetailsViewController.swift, GiniVision/Classes/Core/Screens/Document picker/Gallery/GalleryCoordinator.swift, GiniVision/Classes/Networking/GiniNetworkingScreenAPICoordinator.swift, GiniVision/Tests/DigitalInvoiceTests.swift, GiniVision/Tests/DigitalLineItemViewModelTests.swift, GiniVision/Tests/HelpMenuViewControllerTests.swift, GiniVision/Tests/SupportedFormatsViewControllerTests.swift
Shows return reasons and allows users to pick one when they deselect a line item.
[PIA-846](https://ginis.atlassian.net/browse/PIA-846)
=> Shows and lets users pick return reasons

GiniVision/Classes/Core/Screens/Digital Invoice/LineItem.swift, GiniVision/Classes/Networking/DocumentService.swift
[PIA-819](https://ginis.atlassian.net/browse/PIA-819)
=> Pia 819 return reasons feedback

Documentation/source/Installation.md, Documentation/source/Integration.md, Example/GiniVision.xcodeproj/project.pbxproj, Example/Podfile, Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/Networking/GiniNetworkingScreenAPICoordinator.swift, GiniVision/Classes/Networking/Pinning/GiniNetworkingScreenAPICoordinator+Pinning.swift, GiniVision/Classes/Networking/Pinning/GiniVision+Pinning.swift
https://ginis.atlassian.net/browse/PIA-875
Automatic
=> extented with GiniVisionTrackingDelegate (PIA-875)

Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Networking/GiniNetworkingScreenAPICoordinator.swift
* Fixes an EPS QR Code issue which prevented the `epspayment://` uri to be returned in the extractions when using the default networking implementation.
=> Release 5.5.1

Documentation/source/Event tracking guide.md, Example/Podfile.lock, GiniVision/Classes/Core/GiniVision.swift
[PIA-888](https://ginis.atlassian.net/browse/PIA-888)
=> Pia 888 tracking without networking

GiniVision/Classes/Core/Screens/Document picker/Gallery/GalleryCoordinator.swift
fix a compilation error for Xcode 11
build with Xcode 11.7
Automatic
https://ginis.atlassian.net/browse/PIA-916
=> fix a compilation error for Xcode 11 (PIA-916)

GiniVision/Assets/de.lproj/Localizable.strings, GiniVision/Classes/Core/Screens/Digital Invoice/DigitalInvoiceHeaderCell.swift, GiniVision/Classes/Core/Screens/Digital Invoice/Onboarding/DigitalInvoiceOnboarding.storyboard
=> PIA-1097, PIA-1099

Example/GiniVision.xcodeproj/project.pbxproj, GiniVision/Tests/CameraViewControllerTests.swift
=> GiniVision: fixed test and increase iOS dev target up to 10.2 (PIA-711)

Documentation/source/QR Code scanning guide.md, GiniVision/Classes/Core/Models/GiniQRCodeDocument.swift, GiniVision/Classes/Networking/GiniNetworkingScreenAPICoordinator.swift
- Update documentation of component API regarding QR code handling.
https://ginis.atlassian.net/browse/PIA-1959
=> Update documentation of component API regarding QR code handling
