gini/gini-vision-lib-ios

GiniVision/Classes/GINIMetaInformationManager.swift
A bug has been reported that rotated pictures are a lot bigger in file size than the unrotated original.
I've tracked this down to using 1.0 as JPEG compression level (best precision). This is too much and we usually use 0.2. So now the default is 0.2.
It's easier to test on the simulator. Use a hardcoded image as input. Note it's file size. Go to the review step and rotate the image. Tap "Next" to start analysing. At this point its useful to save the image before it's sent to the file system. This can be done in `GINIReviewContainerViewController->analyse`:
```swift
try! imageData?.write(to: URL(fileURLWithPath:"/Users/<user>/Documents/libTestimage.jpg"), options: .atomic)
```
Check the saved file's size - it shouldn't be bigger than expected (it highly depends on the compression level …
=> Changed the default JPEG compression level to 0.2

Example/GiniVision.xcodeproj/project.pbxproj, Example/GiniVision/Base.lproj/Main.storyboard, Example/Tests/GINICameraViewControllerTests.swift, Example/Tests/GINIOnboardingViewControllerTests.swift, GiniVision/Classes/GINICameraViewController.swift, GiniVision/Classes/GINIOnboardingViewController.swift
To allow a more specific customization of the Gini Vision Library it was requested to make some properties publicly accessible. In this PR `cameraOverlay` (in GINICameraViewController) and `scrollView` (in GINIOnboardingViewController) were made public.
Use Unit Tests and/or try to access the properties in the example projects Component API implementation.
Features needs to be merged into `swift-2.3` and `swift3` branch.
MOBILE-678, MOBILE-679
Github Issues: #19, #22
=> Community requests to make some properties publicly accessible

GiniVision/Classes/GINICameraViewController.swift
We had the following bug:
* Start the Example project
* Choose the Component API
* Rotate the device (use a real device) to landscape
After completing those steps, the camera preview view wasn't properly aligned.
This pull request fixes the issue by updating several constraints on the video preview and rotating the camera feed as the device rotates.
Execute the steps above and verify that the view doesn't cut into the other subviews. **Note** that in landscape the view still respects the 4:3 aspect ratio so it's not going to look really nice. But this is going to be fixed in a subsequent project.
Automatic. Also needs to be cherrypicked in develop and swift-2.3
[MOBILE-698](https://tickets.i.gini.net/issue/MOBILE-698)
=> Bugfix mobile 698 camera resizing

Documentation/deploy-documentation.sh, Documentation/source/changelog.rst, scripts/DOCS_DEPLOY.md, scripts/build-documentation-api.sh, scripts/push-documentation.sh
The pull request contains refactoring / improvements to the automatic documentation deployment scripts:
* Removes an unneeded step of pushing to the `docs` branch
* Adds a Docs Deployment Guide
You have to push a new tagged commit that is not a push request. Note that if you do so, you will deploy the documentation and possible change it. Be careful!
Should be automatic
=> Feature push documentation refactoring

README.md
Our installation guide in `README.md` wasn't mentioning  that we use a custom podspec repository. 
Open the README, scroll to the Cocoapods section and verify that the text acknowledges that we host our podspec ourselves.
Automatic
=> Added a note in the README about adding Gini's custom podspec

Example/Podfile.lock, GiniVision/Classes/ImageMetaInformationManager.swift, GiniVision/Classes/ReviewViewController.swift
In order to better identified identical (only rotated) images in the backend, we are now adding a UUID to the image's EXIF user comment. Also, the rotation angle in degrees should be included. For example:
`UUID=F26AE2F5-4E12-4CD8-A079-0114A11F3C12,RotDeltaDeg=90`
Currently, there are no unit tests, unfortunately. You have to either save the image before uploading and view its EXIF data, or get the uploaded image from the backend
Automatic
=> Adding UUID and rotation to EXIF

GiniVision/Classes/ImageMetaInformationManager.swift
We changed the name of the `UUID` field in EXIF's User Comment for better consistency.
=> Change UUID to ContentId in EXIF's user comment

GiniVision/Classes/AnalysisContainerViewController.swift, GiniVision/Classes/AnalysisViewController.swift, GiniVision/Classes/CameraContainerViewController.swift, GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/OnboardingContainerViewController.swift, GiniVision/Classes/PreferredButtonResource.swift, GiniVision/Classes/PreferredResource.swift, GiniVision/Classes/ReviewContainerViewController.swift, GiniVision/Classes/ReviewViewController.swift
This pull request tackles two problems:
* On customisable buttons, it is impossible to override the default image with a custom text
* On customisable navigation buttons, it is impossible to revert to the default iOS back button (an arrow to the left and a title "Back" or the title of the previous screen).
The problem was that client could override images and titles by providing resources with the same name in their project's asset catalog and `Localizable.strings`, respectively. However, if they supplied a custom text, it would still be overridden by setting the default image, since images take precedence to titles in UIKit. 
Pick a button from the documentation that is subject to customisation (for instance the back button in the review screen). Add an entry to the `Localizable.strings` …
=> Not being able to set custom titles on buttons

Example/GiniVision/ScreenAPIViewController.swift, Example/Podfile.lock, Example/Tests/GINIMetaInformationManagerTests.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/ImageMetaInformationManager.swift, GiniVision/Classes/ReviewViewController.swift
We saw that there was not much change in the uploaded image's quality and size even after changing the JPEG compression level. We debugged that to the `ImageMetainformationManager`. When it was generating compressed images and injecting the EXIF data, there were two conversions between `UIImage` and `NSData`. After the first one, the compression level was lost. This resulted in images with the wrong compression level and it was also wasting processing time.
The fix was to switch to Core Image and compress and annotate the image with EXIF data all in one pass.
Start debugging the example app and look at the console logs while uploading the images. The total size in KB should be printed just before the upload starts. To try different compression levels, change the `JPEGDefaultCompression` …
=> Bugfix image compression

.travis.yml
Sometimes when travis tries to run jobs in parallel, it fails returning `pod install --project-directory=Example --repo-update failed` error. 
Apparently it is due to`xcode8.2` image is not working well with cocoapods dependencies. With `xcode9` image it seems to be solved. 
Restart travis build
Automatic.
#53
=> Fix travis 'pod install' error

Example/Tests/GINIMetaInformationManagerTests.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/GiniImageDocument.swift, GiniVision/Classes/GiniVisionDocument.swift, GiniVision/Classes/ImageMetaInformationManager.swift, GiniVision/Classes/ReviewViewController.swift
`ImageMetaInformationManager` is coupled to the views and they should not know anything about the manager.
Take a picture or import an image an see that all meta information is added to it. Also rotate the picture and check that `RotDeltaDeg` has changed.
Automatic.
Issue #58
=> Uncouple image meta information manager from views

Example/GiniVision.xcodeproj/project.pbxproj, Example/GiniVision/AppDelegate.swift, Example/GiniVision/Base.lproj/Main.storyboard, Example/GiniVision/ComponentAPIAnalysisViewController.swift, Example/GiniVision/ComponentAPICameraViewController.swift, Example/GiniVision/ComponentAPICoordinator.swift, Example/GiniVision/ComponentAPIReviewViewController.swift, Example/GiniVision/Extensions.swift, Example/GiniVision/NoResultViewController.swift, Example/GiniVision/ResultTableViewController.swift, Example/GiniVision/ScreenAPIViewController.swift, Example/GiniVision/SelectAPIViewController.swift, GiniVision/Classes/CameraContainerViewController.swift, GiniVision/Classes/GiniImageDocument.swift, GiniVision/Classes/GiniPDFDocument.swift, GiniVision/Classes/GiniVision.swift, GiniVision/Classes/GiniVisionDocument.swift, GiniVision/Classes/ReviewContainerViewController.swift, GiniVision/Classes/ReviewViewController.swift
Some documents are not reviewable, so they do not have to go through the review screen. On the Component API 
Import a PDF and see that it doesn't go through the review screen. If instead you import an image or take a picture with the camera, it should be reviewable from review screen. 
Also using the "Open with" method, you should have the same result.
Automatic.
Issue #64
=> Remove document validation on review screen

GiniVision/Classes/GiniImageDocument.swift, GiniVision/Classes/ImageMetaInformationManager.swift
GIFs and PNGs images should not have meta information and should not be converted to JPEG. 
Import a PNG or GIF image and see that its bytes count is the same when the image is analyzed.
Automatic.
Issue #61
=> Exif handle for GIFs and PNGs.

GiniVision/Assets/Localizable.strings, GiniVision/Classes/CameraContainerViewController.swift, GiniVision/Classes/CameraNotAuthorizedView.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/Extensions.swift, GiniVision/Classes/FilePickerManager.swift, GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/GiniError.swift
When photo library permission is denied, it should appear a dialog giving the chance to grant it on iOS settings.
Reinstall app, choose _Fotos_ option on file import dialog and deny permissions. Then try again to open the Camera roll and see that the dialog appears.
Automatic.
Issue #65
=> Show photo library permissions denied dialog

Example/GiniVision/ScreenAPIViewController.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/FilePickerManager.swift, GiniVision/Classes/GiniConfiguration.swift
File types supported for file import feature. It should be specified through `GiniConfiguration`, being `none` by default.
Set `fileImportSupportedTypes` to `.all` and see that file import feature is enabled for all types. If instead `.pdf` is set, the app will only handle PDF files (not pictures).
In case that none is specified, it should handle all file types (pictures and pdfs)
Automatic.
Issue #59
=> File types supported toggle for file import feature

Example/GiniVision/SelectAPIViewController.swift, GiniVision/Classes/CameraContainerViewController.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/GiniError.swift, GiniVision/Classes/GiniVisionDocument.swift
Apart from the default document validations (file size, file type...), there should be possible to add custom validations.
Open the example app, go to the camera screen (either Screen or Component API) and try to import a file with a size higher than 5MB.
Automatic.
Issue #82
=> Custom document validations

GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/FilePickerManager.swift, GiniVision/Classes/GiniVision.swift
- On iOS 9 devices when trying to open the Gallery for the first time, after granting the permissions the gallery is not shown.
- Camera preview orientation is not correct when capturing is initialized on landscape (only iPad).
Also clarified documentation for GiniVision class.
Run the example app, rotate the device to landscape orientation and open either Screen API or Component API to see that the camera has the correct orientation. 
Also with an iOS 9 device which has never had the app installed (this is important, permissions flags are not reset after uninstalling), run the app and import a picture from the gallery.
Automatic.
Issue #141
=> Minor fixes

Jenkinsfile
Since all the jobs are failing in Jenkins due to a problem with `xcpretty` and Jenkins encoding, `xcpretty` will be removed until Jenkins encoding can be fixed.
Check that 
Automatic
#147
=> Removed Xcpretty from Jenkinsfile

Example/Podfile.lock, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/ContainerNavigationController.swift, GiniVision/Classes/FilePickerManager.swift, GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/GiniVisionUtils.swift
Added status bar style setting to GiniConfiguration, so now it can be customized. It works both when `UIViewControllerBasedStatusBarAppearance` is enabled and disabled. 
Run the example app with `UIViewControllerBasedStatusBarAppearance` as NO in the Info.plist file. Check that status bar changes once the GVL is launched.
Do the same but with `UIViewControllerBasedStatusBarAppearance` as `YES` and check that it is also working.
Automatic.
Issue #144
=> Feature custom status bar

GiniVision/Classes/AnalysisViewController.swift, GiniVision/Classes/CameraNotAuthorizedView.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/CaptureSuggestionsCollectionCell.swift, GiniVision/Classes/CaptureSuggestionsCollectionHeader.swift, GiniVision/Classes/CaptureSuggestionsView.swift, GiniVision/Classes/GiniVisionUtils.swift, GiniVision/Classes/ImageAnalysisNoResultsViewController.swift, GiniVision/Classes/NoticeView.swift, GiniVision/Classes/OnboardingContainerViewController.swift, GiniVision/Classes/OnboardingPage.swift, GiniVision/Classes/OnboardingViewController.swift, GiniVision/Classes/OpenWithTutorialCollectionCell.swift, GiniVision/Classes/OpenWithTutorialCollectionHeader.swift, GiniVision/Classes/PDFInformationView.swift, GiniVision/Classes/QRCodeDetectedPopupView.swift, GiniVision/Classes/ReviewViewController.swift, GiniVision/Classes/SupportedFormatsTableViewCell.swift, GiniVision/Classes/ToolTipView.swift
There was a typo in `Constraints` class, being `Contraints` instead of `Constraints.`
Nothing to test. 
Automatic
Issue #150
=> Fix Constraints class typo

GiniVision/Classes/FilePickerManager.swift
When presenting a UIDocumentViewController on iPads, the view controller that presents it doesn't disappear.
Run the app on an iPad, try to import a document and see that the status bar is changed properly.
Automatic
=> Fixed issue on UIDocumentViewController status bar for iPads

GiniVision/Classes/CameraViewController.swift
When using the simulator it was not possible to use the default image when tapping the capture button.
Run the app with the simulator and press capture button.
Automatic
Issue #170
=> Fixed simulator not using the default image.

Example/Podfile.lock, GiniVision/Classes/Networking/APIService.swift, GiniVision/Classes/Networking/Extensions/GiniScreenAPICoordinator+Networking.swift
In order to track when a user has cancelled the analysis, it is necessary to handle the polling of a document outside of the API SDK.
The printed logs will be shown in a future custom Logger, so they will be removed once the logger is created in a different PR.
Run the app and analyze a document. In the middle of the analysis go back and see that the log shows the polling status.
Automatic
Issue #174
=> Handle polling outside of API SDK

GiniVision/Classes/Core/CameraViewController.swift, GiniVision/Classes/Core/DocumentPickerCoordinator.swift
PDF file import should be disabled if there is already an image imported/taken
Run the app, take a picture and try to import a PDF from the Files explorer.
Automatic
=> Restrict pdfs when image(s) have been already selected

Example/Tests/GalleryCoordinatorDelegateMock.swift, Example/Tests/GalleryCoordinatorTests.swift, Example/Tests/GalleryManagerMock.swift, Example/Tests/ImagePickerViewControllerDelegateMock.swift, Example/Tests/ImagePickerViewControllerTests.swift, GiniVision/Classes/Core/CameraViewController.swift, GiniVision/Classes/Core/DocumentPickerCoordinator.swift, GiniVision/Classes/Core/Gallery/AlbumsPickerViewController.swift, GiniVision/Classes/Core/Gallery/Asset.swift, GiniVision/Classes/Core/Gallery/GalleryCoordinator.swift, GiniVision/Classes/Core/Gallery/GalleryManager.swift, GiniVision/Classes/Core/Gallery/ImagePickerCollectionViewCell.swift, GiniVision/Classes/Core/Gallery/ImagePickerViewController.swift, GiniVision/Classes/Core/GiniVisionUtils.swift, GiniVision/Classes/Core/MultipageReviewTransitionAnimator.swift
There was a couple of issues related to gallery:
- Opening the gallery before giving access to it resulted in a blank collection since images weren't cached after that.
- When fetching assets from the OS, if the asset was in iCloud it returned `nil`.
Make a clean install of the app and try to open the gallery after granting permissions to it. Also select an asset from iCloud.
Automatic
=> Fix gallery issues

Example/GiniVision.xcodeproj/project.pbxproj, Example/GiniVision.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Example/GiniVision/AppCoordinator.swift, Example/Tests/GINICameraViewControllerTests.swift, Example/Tests/GINIQRCodeDocumentTests.swift, Example/Tests/GINIVisionDocumentTests.swift, Example/Tests/GalleryManagerMock.swift, Example/Tests/GiniScreenAPICoordinatorTests.swift, Example/Tests/GiniVisionDelegateMock.swift, Example/Tests/GiniVisionDocumentValidatorTests.swift, GiniVision/Classes/Core/Camera.swift, GiniVision/Classes/Core/CameraViewController.swift, GiniVision/Classes/Core/DocumentPickerCoordinator.swift, GiniVision/Classes/Core/Extensions/UIViewController.swift, GiniVision/Classes/Core/Gallery/GalleryCoordinator.swift, GiniVision/Classes/Core/Gallery/GalleryManager.swift, GiniVision/Classes/Core/GiniImageDocument.swift, GiniVision/Classes/Core/GiniPDFDocument.swift, GiniVision/Classes/Core/GiniQRCodeDocument.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator+Analysis.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator+Camera.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator+Review.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator.swift, GiniVision/Classes/Core/GiniVision.swift, GiniVision/Classes/Core/GiniVisionDocument.swift, GiniVision/Classes/Core/GiniVisionDocumentValidator.swift, GiniVision/Classes/Core/GiniVisionUtils.swift
To avoid raveled and unreadable code between the components of the application, it has been decoupled the validation from the camera screen, being done outside of it. Also the pickers has been also decoupled from the camera so it is now more clear. This eases the validation and flow between different components, being easier to use with the Component API.
Run the Example app in single page mode, disable internet connection in the device and try to analyze a document.
Automatic
=> Refactor document validation

Documentation/source/Changelog.md, Example/Example Swift/ComponentAPICoordinator.swift, Example/Example Swift/Info.plist, GiniVision/Classes/Core/GiniScreenAPICoordinator.swift, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Networking/MultipageDocumentsService.swift, GiniVision/Classes/Networking/SinglePageDocumentsService.swift
When using open with, the documents were not being uploaded. Also there were problems with PDF and QR code document upload, since the analysis might start when the document wasn't uploaded.
Open _Files_ app and open a file from there. Also try to analyze a QR code and check that you get results.
Automatic
=> Fixed open with and QRcode/PDF document upload

Example/GiniVision.xcodeproj/project.pbxproj
When building ObjC target builds were failing the first time due to an issue with the Credentials.plist file.
Run the build in Jenkins and see that it is not failing in the Build ObjC stage.
Automatic
=> Fixed issue with failing builds when building ObjC target

Example/Example Swift/ComponentAPICoordinator.swift, Example/Example Swift/MultipageDocumentService.swift, GiniVision/Classes/Core/CameraViewController.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator+Camera.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator.swift
When a user tried to analyze a PDF/QRCode document, it wasn't analyzed because the analysis wasn't triggered after the document was uploaded.
Also when scanning a QR code, this wasn't processed properly, being uploaded twice when it was validated (tap on the popup button triggered the upload again).
Run the Example app, scan a QR code and check that you obtain results afterwards.
Automatic
#223
=> Fixed QR code and PDF documents analysis

Example/Example Swift/ComponentAPICoordinator.swift, Example/Example Swift/DocumentServiceProtocol.swift, Example/Example Swift/MultipageDocumentService.swift, Example/Example Swift/SinglePageDocumentService.swift, Example/Example Swift/UIViewController.swift, Example/Tests/GINIComponentAPICoordinatorTests.swift, GiniVision/Classes/Core/AnalysisViewController.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator+Analysis.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator+Camera.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator.swift, GiniVision/Classes/Core/GiniVision.swift, GiniVision/Classes/Core/Multipage Review/MultipageReviewPagesCollectionCell.swift, GiniVision/Classes/Core/Multipage Review/MultipageReviewPagesCollectionFooter.swift, GiniVision/Classes/Core/Multipage Review/MultipageReviewViewController.swift, GiniVision/Classes/Networking/DocumentServiceProtocol.swift, GiniVision/Classes/Networking/Extensions/GiniScreenAPICoordinator+Networking.swift, GiniVision/Classes/Networking/SinglePageDocumentsService.swift
When there is an error in the analysis or uploading a document, it has to be shown in the analysis screen. For the uploading doesn't apply for images when multipage is enabled, since the error will be shown in the multipage screen.
Also fixed minor issue with auto-layout in page cell.
Run the Example app, disable the internet connection, scan a qr code and see that an error is shown in the analysis screen.
Automatic
#243
=> Added analysis screen error view

Example/GiniVision.xcodeproj/project.pbxproj, Example/Podfile.lock, Example/Tests/GINICameraViewControllerTests.swift, Example/Tests/OpaqueViewTests.swift, GiniVision/Classes/CameraViewController.swift, GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/OpaqueViewFactory.swift
The background view color when the tool tip was shown in the camera screen might be misleading for the user. Now it is possible to customize it with a different style: 
- Blurred with light style
- Blurred with dark style
- Dimmed (only dark)
Change the value of `GiniConfiguration.toolTipOpaqueBackgroundStyle` and run the app for the first time. Open the screen API and check that the background shown below the tool tip matches the value specified in the property.
Automatic
#247
=> Added customizable opaque background view style when the tool tip is shown 

Example/Example Swift/ComponentAPICoordinator.swift, GiniVision/Classes/Core/Camera.swift, GiniVision/Classes/Core/CameraViewController.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator+Camera.swift, GiniVision/Classes/Core/GiniScreenAPICoordinator.swift
Now QR code documents are validated in the camera screen show there is no need to validate them outside of it. This implies that once the document (either image or QR code) has been capture in the camera, both are processed in the same way.
Run the example app, scan a QR code and check that it is processed as it was before.
Automatic
#242
=> Move QR code validation to camera

Example/Podfile.lock, Example/Tests/GINIOpenWithTutorialViewControllerTests.swift, GiniVision/Classes/GiniConfiguration.swift, GiniVision/Classes/OpenWithTutorialViewController.swift
Now the drag and drop step within the open with tutorial is optional.
Change the `shouldShowDragAndDropTutorial` in the `GiniConfiguration` to false and check that the last step is not shown.
Automatic
=> Added flag for drag and drop in Open with tutorial

Documentation/source/Customization guide.md, Example/Tests/MultipageReviewPagesCollectionCellTests.swift, GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/Screens/Multipage Review/MultipageReviewPagesCollectionCell.swift
Both the selected line and draggable icon are now customizable in the multipage page collection items.
Change the configuration properties in the `GiniConfiguration` and run the Example app to check that it is working.
Automatic
=> Added missing styling for pages in multipage screen

GiniVision/Classes/Core/Screens/Multipage Review/MultipageReviewPagesCollectionFooter.swift
Fixed issue with vertical ambiguity in "Add image" cell in the MultipageReview screen, that was only affecting iOS 12.
Run the example app in an device running iOS 12 and check that the cell is properly shown.
Automatic
=> Fixed issue with vertical ambiguity in view

GiniVision/Classes/Core/Screens/Document picker/Gallery/GalleryCoordinator.swift
Changed open button text color in ImagePickerViewController, so now it takes the GiniConfiguration bar item color instead of being always white
Change the `navigationBarItemTintColor` property in the `GiniConfiguration` and check that the button text color matches that value
Automatic
=> Fix color for Open button text in ImagePickerViewController

Example/Podfile, Example/Podfile.lock
The Example app podfile was pointing to the wrong version of the Gini API SDK.
Automatic
=> Remove develop branch reference in Podfile

Documentation/source/Integration.md, Example/Example ObjC/ScreenAPIViewController.m, Example/Example Swift/AppCoordinator.swift, Example/Example Swift/ComponentAPIDocumentServiceProtocol.swift, Example/Example Swift/ComponentAPIDocumentsService.swift, Example/Example Swift/ScreenAPICoordinator.swift, Example/Podfile.lock, Example/Tests/DocumentServiceMock.swift, Example/Tests/ScreenAPICoordinatorTests.swift, GiniVision.podspec, GiniVision/Classes/Networking/DocumentServiceProtocol.swift, GiniVision/Classes/Networking/DocumentsService.swift, GiniVision/Classes/Networking/Extensions/GiniScreenAPICoordinator+Networking.swift, GiniVision/Classes/Networking/Extensions/GiniVision+GiniVisionDelegate.swift, GiniVision/Classes/Networking/Pinning/GiniScreenAPICoordinator+Pinning.swift, GiniVision/Classes/Networking/Pinning/GiniVision+Pinning.swift
Added document upload metadata support for the networking plugin. Additionally, it has been added to the Component API example as well.
Run the example app, and check that when creating partial and composite documents, the metadata headers are added to the request (in both the Screen API and Component API)
Manual
=> Documents metadata for networking plugin

Documentation/source/Integration.md, GiniVision/Classes/Networking/AccountingDocumentService.swift, GiniVision/Classes/Networking/Extensions/GiniScreenAPICoordinator+Networking.swift
The cancellation for document creation was missing in the accounting document service. Also a warning for multipage support was missing in the integration guide.
Run the example app with .accounting API, take a picture, go to the analysis and once there cancel it.
Automatic
=> Add missing document creation cancellation

GiniVision/Tests/GiniVisionFontTests.swift
The `xcodebuild` command is not able to check the `@available` attribute in every test case, failing when Cocoapods tried to test against the minimun iOS version (9.3) during `pod lib lint` execution. 
Run `pod lib lint` 
Automatic
=> Fixed tests issue

Example/Podfile.lock, GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/Screens/Document picker/DocumentPickerCoordinator.swift
If using a custom UIAppearance in the host app, there were some issues that could affect the document explorer screen in the GVL for iOS >= 11.0. To fix this, a new property in the `GiniConfiguration` was added, allowing the tint color customization.
Customize the UIAppearance for the UINavigationBar, UISearchBar and UIBarButtonItem, and launch the document explorer in the GVL to check that there is no issues.
Automatic
=> Add tint color customization for Document Explorer screen

GiniVision/Classes/Core/Screens/Analysis/AnalysisViewController.swift, GiniVision/Classes/Core/Screens/Camera/CameraViewController.swift, GiniVision/Classes/Core/Screens/Onboarding/OnboardingPage.swift, GiniVision/Classes/Core/Screens/Onboarding/OnboardingViewController.swift, GiniVision/Classes/Core/Screens/Review/ReviewViewController.swift
Some methods weren't exposed in Obj-C with the `@objc` attribute.
Try to instantiate these files in the Objective C Example
Automatic
#308
=> Switch to @objcMembers attribute in Component classes.

Example/Example Swift/ComponentAPIDocumentServiceProtocol.swift, Example/Example Swift/ComponentAPIDocumentsService.swift, Example/GiniVision.xcodeproj/project.pbxproj, Example/Podfile.lock, Example/Tests/DocumentServiceMock.swift, GiniVision.podspec, GiniVision/Classes/Core/Screens/Analysis/AnalysisViewController.swift, GiniVision/Classes/Core/Screens/Document picker/DocumentPickerCoordinator.swift, GiniVision/Classes/Core/Screens/Help/Open with tutorial/OpenWithTutorialViewController.swift, GiniVision/Classes/Networking/AccountingDocumentService.swift, GiniVision/Classes/Networking/DocumentService.swift, GiniVision/Classes/Networking/DocumentServiceProtocol.swift
There was an issue with framework linking when using the networking module in latest versions of Cocoapods. To solve it, an explicit declaration of Bolts has been added in the _GiniVision_ podspec.
Kudos to @couchdeveloper for spotting this issue 💯.
Run `Pod install` in the Example app, build the project and see that there aren't issues.
Automatic
=> Fixes implicit dependency issue with Bolts

CameraMock.swift, GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/Screens/Camera/Camera.swift, GiniVision/Classes/Core/Screens/Camera/CameraPreviewView.swift, GiniVision/Classes/Core/Screens/Camera/CameraPreviewViewController.swift, GiniVision/Classes/Core/Screens/Camera/CameraViewController+Constraints.swift, GiniVision/Classes/Core/Screens/Camera/CameraViewController.swift, GiniVision/Tests/CameraPreviewViewControllerTests.swift, GiniVision/Tests/CameraViewControllerTests.swift
All camera preview related functionality has been extracted from the `CameraViewController` to the new `CameraPreviewViewController`.
Run the Example and check that everything was working as expected.
Automatic
=> Extract camera preview to a different view controller

Example/Podfile.lock, GiniVision/Classes/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift
Fixed issue with Onboarding transition when the Screen API was presented modally.
Present the Screen API from a UIViewController (not UINavigationController), with a `coverVertical` transition, and check that the Onboarding screen is presented with a `.crossDisolve` style.
Automatic
=> Fixed Onboarding transition issue

Example/Example Swift/AppCoordinator.swift, Example/Podfile.lock, GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/Screens/Document picker/DocumentPickerCoordinator.swift
Fixes an issue with the navigation bar appearance when using a custom tint color.
Change the UINavigation appearance and set the tint color to check that it's changed.
Automatic
=> Fix navigation bar issue after picking a document

GiniVision/Classes/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift
Improves the navigation to the help screen. Now when there is only one item, it skips the menu and shows it directly.
Set both open with and supported formats flags to `false` in the `GiniConfiguration` and check that is working.
Automatic
=> Improve navigation to the help screens

GiniVision/Classes/Core/Helpers/GiniVisionDocumentValidator.swift, GiniVision/Tests/GiniVisionDocumentValidatorTests.swift
When using an empty file, it should also prevent to upload it to the backend.
Run the example app and select an empty file from the file browser
Automatic
=> Add file check for empty files

.gitignore, Documentation/source/Customization guide.md
The image assets for the flash toggle icon were omitted from the customization guide and have been added now.
[PIA-282](https://ginis.atlassian.net/browse/PIA-282)
=> Added flash toggle image asset names to customization guide

Example/Example ObjC/ScreenAPIViewController.m, Example/Podfile.lock, GiniVision/Classes/Networking/AnalysisResult.swift
Keeping a reference to the Gini ViewController so that the `GiniScreenAPICoordinator` instance is available when the send feedback block is invoked from the results screen.
=> Fix feedback sending in Obj-C example

Example/Podfile.lock, GiniVision/Classes/Core/Screens/Multipage Review/MultipageReviewViewController.swift, GiniVision/Tests/MultipageReviewViewControllerTests.swift
We fall back to position 0 if the item position is out of bounds. Also if the pages array is empty the item selection does nothing.
Run the MultipageReviewViewControllerTests.
#345, [PIA-291](https://ginis.atlassian.net/browse/PIA-291)
=> Fallback for out of bounds item positions

Example/Example Swift/AppCoordinator.swift, Example/Example Swift/ComponentAPIOnboardingViewController.swift, Example/Example Swift/NoResultViewController.swift, Example/Example Swift/ResultTableViewController.swift, Example/Example Swift/RootNavigationController.swift, Example/Example Swift/SelectAPIViewController.swift, Example/Example Swift/SettingsViewController.swift, Example/Example Swift/UIViewController.swift, Example/Podfile.lock, GiniVision/Classes/Core/Extensions/UIViewController.swift, GiniVision/Classes/Core/Screens/Analysis/AnalysisViewController.swift, GiniVision/Classes/Core/Screens/Camera/CameraButtonsViewController.swift, GiniVision/Classes/Core/Screens/Camera/CameraPreviewViewController.swift, GiniVision/Classes/Core/Screens/Camera/CameraViewController.swift, GiniVision/Classes/Core/Screens/Document picker/DocumentPickerCoordinator.swift, GiniVision/Classes/Core/Screens/Document picker/Gallery/AlbumsPickerViewController.swift, GiniVision/Classes/Core/Screens/Document picker/Gallery/ImagePickerViewController.swift, GiniVision/Classes/Core/Screens/Help/HelpMenuViewController.swift, GiniVision/Classes/Core/Screens/Help/No results /ImageAnalysisNoResultsViewController.swift, GiniVision/Classes/Core/Screens/Help/Open with tutorial/OpenWithTutorialViewController.swift, GiniVision/Classes/Core/Screens/Help/Supported formats/SupportedFormatsViewController.swift, GiniVision/Classes/Core/Screens/Multipage Review/MultipageReviewViewController.swift, GiniVision/Classes/Core/Screens/Onboarding/OnboardingContainerViewController.swift, GiniVision/Classes/Core/Screens/Onboarding/OnboardingViewController.swift, GiniVision/Classes/Core/Screens/Review/ReviewViewController.swift, GiniVision/Tests/GalleryCoordinatorTests.swift, GiniVision/Tests/HelpMenuViewControllerTests.swift, Jenkinsfile
We opted to only allow light mode. Supporting dark mode entails a thorough redesign of all the screens. In the future we might add support for dark mode.
Build with Xcode 11 and run on an iOS 13 device. Switch to dark mode. The example app should remain in light mode.
PIA-302
=> Fix dark mode issues

GiniVision/Classes/Core/Extensions/UIImage.swift
In iOS 13 the qr code image was not rendered. This fixes it by converting the CI image to a CG image before passing it to a UIImage to be rendered.
Build with Xcode 11 and run on an iOS 13 device. Scan a BezahlCode and the qr code should be shown in the popup.
PIA-347
=> Fix qr code image in the popup

GiniVision/Classes/Core/Screens/Document picker/Gallery/GalleryManager.swift
The image caching by `PHCachingImageManager` results in large memory use if the user has many pictures on their phone. 
This PR reduces the number of cached images to the 5 last ones. The performance doesn't seem affected for some of the earlier ones anyway.
=> PIA-374: Excessive memory usage by the image gallery.

Example/Podfile.lock
Mostly important to force an update for Gini which still points to staging in the current Podfile.lock.
=> Updated pods.

Example/Podfile.lock, GiniVision.podspec
I've found a cheeky way to fix the lib lint which doesn't require the workaround that results in the library being much bigger. You simply need to remove the sim runtimes for iOS earlier than 12 from the build machine and the utility will be forced to use the runtime that doesn't have the bug that's causing the problems including AVFoundation in the test target.
=> Remove 'ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES' => 'YES'

GiniVision/Classes/Core/Extensions/UIViewController.swift, GiniVision/Classes/Core/GiniConfiguration.swift, GiniVision/Classes/Core/Helpers/PreferredButtonResource.swift, GiniVision/Classes/Core/Screens/Help/HelpMenuViewController.swift, GiniVision/Classes/Core/Screens/Onboarding/OnboardingContainerViewController.swift, GiniVision/Classes/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift
The asset catalogue in a Xamarin project doesn't seem to override the GVL asset catalogue, so I'm allowing to inject preferred resources through GiniConfiguration.
=> PIA-687: iOS: Allow image asset customisation in Xamarin

Example/Podfile.lock, GiniVision/Classes/Networking/GiniNetworkingScreenAPICoordinator.swift
Simplifies condition to show no results screen: checks only that there is at least one extraction.
[PIA-897](https://ginis.atlassian.net/browse/PIA-897)
=> 5.x: Fixes EPS QR Codes when using the default networking pod

Example/Example Swift/ComponentAPIDocumentsService.swift, GiniVision/Classes/Networking/DocumentServiceProtocol.swift
While reproducing [PIA-1353](https://ginis.atlassian.net/browse/PIA-1353) I found the cause of errors not being shown on the analysis screen.
=> Fix showing errors on the analysis screen

Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/Core/GiniVisionVersion.swift
* Updates Gini API SDK to 1.0.1 and sets the minimum iOS version to 12 for the `GiniVision/Networking+Pinning` pod.
=> Release version 5.7.1

GiniVision/Classes/Core/Screens/Multipage Review/MultipageReviewViewController.swift
MultipageReviewViewController: Detected memory leak (PIA-1778)
during the collection view batch update.
Run instruments -> leaks without and with those changes
Automatic
https://ginis.atlassian.net/browse/PIA-1778
=> MultipageReviewViewController: Detected memory leak (PIA-1778)

Example/Podfile.lock, GiniVision.podspec, GiniVision/Classes/Core/GiniVisionVersion.swift, GiniVision/Classes/Core/Screens/Camera/CameraViewController.swift
fix(GiniVisionLibrary): Fix condition for showing file import sheet and tooltip for Component API.
The problem exists because showing import is coupled with Screen API and we need to refactor it in future releases.
Start Component API after a fresh install.
=> Fix import sheet
